version: "2"

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=112233
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=112233

  app:
    image: nextcloud:20-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=112233

  emby:
    image: emby/embyserver
    restart: always
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /var/lib/docker/volumes/nextcloud-deploy_nextcloud/_data/data/guilherme/files/Movies:/mnt/movies
    environment:
      - UID=1000
      - GID=100
      - GIDLIST=100

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - nextcloud:/var/www/html:ro

volumes:
  db:
  nextcloud:
